# NATURALGEN = 0, Showing Natural
#     Low Rate [◇]       Wolf [◆]
execute if entity @s[tag=showNatural] unless score NATURALGEN _plushieSettings matches 1 if score CUSTOMGEN _plushieSettings matches 1 if score RATE_C _plushieSettings matches 3 run tellraw @s ["",{"text":" \u0020 \u0020 Low Rate ","color":"yellow"},{"text":"[\u25c7]","color":"gray"},{"text":" \u0020 \u0020 \u0020 Wolf ","color":"green","hoverEvent":{"action":"show_text","value":"The Custom Spawner mob is using the last rate setup for this entity."}},{"text":"[\u25c6]","color":"aqua"},{"text":"\n "}]
execute if entity @s[tag=showNatural] unless score NATURALGEN _plushieSettings matches 1 if score CUSTOMGEN _plushieSettings matches 1 unless score RATE_C _plushieSettings matches 3 run tellraw @s ["",{"text":" \u0020 \u0020 Low Rate ","color":"yellow"},{"text":"[\u25c7]","color":"gray"},{"text":" \u0020 \u0020 \u0020 Wolf ","color":"dark_gray"},{"text":"[\u25c6]","color":"aqua"},{"text":"\n "}]
execute if entity @s[tag=showNatural] unless score NATURALGEN _plushieSettings matches 1 unless score CUSTOMGEN _plushieSettings matches 1 run tellraw @s ["",{"text":" \u0020 \u0020 Low Rate ","color":"yellow"},{"text":"[\u25c7]","color":"gray"},{"text":" \u0020 \u0020 \u0020 Wolf ","color":"dark_gray"},{"text":"[\u25c6]","color":"aqua"},{"text":"\n "}]
# NATURALGEN = 1, Showing Natural, RATE not 1
#     Low Rate [◇]       Wolf [◆]
execute if entity @s[tag=showNatural] if score NATURALGEN _plushieSettings matches 1 if score RATE _plushieSettings matches 0 run tellraw @s ["",{"text":" \u0020 \u0020 Low Rate ","color":"yellow"},{"text":"[\u25c6]","color":"green"},{"text":" \u0020 \u0020 \u0020 Wolf ","color":"gold"},{"text":"[\u25c6]","color":"aqua"},{"text":"\n "}]
# NATURALGEN = 1, Showing Natural, RATE = 1
#     Low Rate [◆]       Wolf [◆]
execute if entity @s[tag=showNatural] if score NATURALGEN _plushieSettings matches 1 unless score RATE _plushieSettings matches 0 run tellraw @s ["",{"text":" \u0020 \u0020 Low Rate ","color":"yellow"},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/low_rate"}},{"text":"\u25c7","color":"green","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/low_rate"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/low_rate"}},{"text":" \u0020 \u0020 \u0020 Wolf ","color":"gold"},{"text":"[\u25c6]","color":"aqua"},{"text":"\n "}]



# CUSTOMGEN = 0, Showing Custom
#     Low Rate [◇]       Wolf [◇]
execute if entity @s[tag=showCustom] unless score CUSTOMGEN _plushieSettings matches 1 if score NATURALGEN _plushieSettings matches 1 run tellraw @s ["",{"text":" \u0020 \u0020 Low Rate ","color":"yellow"},{"text":"[\u25c7]","color":"gray"},{"text":" \u0020 \u0020 \u0020 Wolf ","color":"gold"},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"\u25c7","color":"aqua","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"\n "}]
execute if entity @s[tag=showCustom] unless score CUSTOMGEN _plushieSettings matches 1 unless score NATURALGEN _plushieSettings matches 1 run tellraw @s ["",{"text":" \u0020 \u0020 Low Rate ","color":"yellow"},{"text":"[\u25c7]","color":"gray"},{"text":" \u0020 \u0020 \u0020 Wolf ","color":"dark_gray"},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"\u25c7","color":"aqua","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"\n "}]
# CUSTOMGEN = 1, Showing Custom, RATE not 1
#     Low Rate [◇]       Wolf [◇]
execute if entity @s[tag=showCustom] if score CUSTOMGEN _plushieSettings matches 1 if score NATURALGEN _plushieSettings matches 1 if score RATE_C _plushieSettings matches 0 run tellraw @s ["",{"text":" \u0020 \u0020 Low Rate ","color":"yellow"},{"text":"[\u25c6]","color":"green"},{"text":" \u0020 \u0020 \u0020 Wolf ","color":"gold"},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"\u25c7","color":"aqua","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"\n "}]
execute if entity @s[tag=showCustom] if score CUSTOMGEN _plushieSettings matches 1 unless score NATURALGEN _plushieSettings matches 1 if score RATE_C _plushieSettings matches 0 run tellraw @s ["",{"text":" \u0020 \u0020 Low Rate ","color":"yellow"},{"text":"[\u25c6]","color":"green"},{"text":" \u0020 \u0020 \u0020 Wolf ","color":"dark_gray"},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"\u25c7","color":"aqua","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"\n "}]
execute if entity @s[tag=showCustom] if score CUSTOMGEN _plushieSettings matches 1 unless score NATURALGEN _plushieSettings matches 1 if score RATE_C _plushieSettings matches 3 run tellraw @s ["",{"text":" \u0020 \u0020 Low Rate ","color":"yellow"},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/low_rate"}},{"text":"\u25c7","color":"green","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/low_rate"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/low_rate"}},{"text":" \u0020 \u0020 \u0020 Wolf ","color":"green","hoverEvent":{"action":"show_text","value":"The Custom Spawner mob is using the last rate setup for this entity."}},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"\u25c7","color":"aqua","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"\n "}]

# CUSTOMGEN = 1, Showing Custom, RATE = 1
#     Low Rate [◆]       Wolf [◇]
execute if entity @s[tag=showCustom] if score CUSTOMGEN _plushieSettings matches 1 if score NATURALGEN _plushieSettings matches 1 unless score RATE_C _plushieSettings matches 0 run tellraw @s ["",{"text":" \u0020 \u0020 Low Rate ","color":"yellow"},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/low_rate"}},{"text":"\u25c7","color":"green","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/low_rate"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/low_rate"}},{"text":" \u0020 \u0020 \u0020 Wolf ","color":"gold"},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"\u25c7","color":"aqua","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"\n "}]
execute if entity @s[tag=showCustom] if score CUSTOMGEN _plushieSettings matches 1 unless score NATURALGEN _plushieSettings matches 1 unless score RATE_C _plushieSettings matches 0 unless score RATE_C _plushieSettings matches 3 run tellraw @s ["",{"text":" \u0020 \u0020 Low Rate ","color":"yellow"},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/low_rate"}},{"text":"\u25c7","color":"green","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/low_rate"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/low_rate"}},{"text":" \u0020 \u0020 \u0020 Wolf ","color":"dark_gray"},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"\u25c7","color":"aqua","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_natural"}},{"text":"\n "}]
