# NATURALGEN = 0, Showing Natural
#     Middle Rate [◇]       Custom [◇]
execute if entity @s[tag=showNatural] unless score NATURALGEN _plushieSettings matches 1 if score CUSTOMGEN _plushieSettings matches 1 run tellraw @s ["",{"text":" \u0020 \u0020 Middle Rate ","color":"yellow"},{"text":"[\u25c7]","color":"gray"},{"text":"    Custom ","color":"gold","hoverEvent":{"action":"show_text","value":"Let's you decide what mobs should be use to spawn plushies (Default: minecraft:pig). \u00a7f[ \u00a79Config file located inside datapack at: \u00a75data/plushie_settings/tags/entity_types/spawner.json \u00a7f]"}},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"\u25c7","color":"aqua","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"\n "}]
execute if entity @s[tag=showNatural] unless score NATURALGEN _plushieSettings matches 1 unless score CUSTOMGEN _plushieSettings matches 1 run tellraw @s ["",{"text":" \u0020 \u0020 Middle Rate ","color":"yellow"},{"text":"[\u25c7]","color":"gray"},{"text":"    Custom ","color":"dark_gray","hoverEvent":{"action":"show_text","value":"Let's you decide what mobs should be use to spawn plushies (Default: minecraft:pig). \u00a7f[ \u00a79Config file located inside datapack at: \u00a75data/plushie_settings/tags/entity_types/spawner.json \u00a7f]"}},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"\u25c7","color":"aqua","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"\n "}]
# NATURALGEN = 1, Showing Natural, RATE not 1
#     Middle Rate [◆]       Custom [◇]
execute if entity @s[tag=showNatural] if score NATURALGEN _plushieSettings matches 1 if score CUSTOMGEN _plushieSettings matches 1 if score RATE _plushieSettings matches 1 run tellraw @s ["",{"text":" \u0020 \u0020 Middle Rate ","color":"yellow"},{"text":"[\u25c6]","color":"green"},{"text":"    Custom ","color":"gold","hoverEvent":{"action":"show_text","value":"Let's you decide what mobs should be use to spawn plushies (Default: minecraft:pig). \u00a7f[ \u00a79Config file located inside datapack at: \u00a75data/plushie_settings/tags/entity_types/spawner.json \u00a7f]"}},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"\u25c7","color":"aqua","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"\n "}]
execute if entity @s[tag=showNatural] if score NATURALGEN _plushieSettings matches 1 unless score CUSTOMGEN _plushieSettings matches 1 if score RATE _plushieSettings matches 1 run tellraw @s ["",{"text":" \u0020 \u0020 Middle Rate ","color":"yellow"},{"text":"[\u25c6]","color":"green"},{"text":"    Custom ","color":"dark_gray","hoverEvent":{"action":"show_text","value":"Let's you decide what mobs should be use to spawn plushies (Default: minecraft:pig). \u00a7f[ \u00a79Config file located inside datapack at: \u00a75data/plushie_settings/tags/entity_types/spawner.json \u00a7f]"}},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"\u25c7","color":"aqua","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"\n "}]
# NATURALGEN = 1, Showing Natural, RATE = 1
#     Middle Rate [◇]       Custom [◇]
execute if entity @s[tag=showNatural] if score NATURALGEN _plushieSettings matches 1 if score CUSTOMGEN _plushieSettings matches 1 unless score RATE _plushieSettings matches 1 run tellraw @s ["",{"text":" \u0020 \u0020 Middle Rate ","color":"yellow"},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/middle_rate"}},{"text":"\u25c7","color":"green","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/middle_rate"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/middle_rate"}},{"text":"    Custom ","color":"gold","hoverEvent":{"action":"show_text","value":"Let's you decide what mobs should be use to spawn plushies (Default: minecraft:pig). \u00a7f[ \u00a79Config file located inside datapack at: \u00a75data/plushie_settings/tags/entity_types/spawner.json \u00a7f]"}},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"\u25c7","color":"aqua","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"\n "}]
execute if entity @s[tag=showNatural] if score NATURALGEN _plushieSettings matches 1 unless score CUSTOMGEN _plushieSettings matches 1 unless score RATE _plushieSettings matches 1 run tellraw @s ["",{"text":" \u0020 \u0020 Middle Rate ","color":"yellow"},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/middle_rate"}},{"text":"\u25c7","color":"green","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/middle_rate"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/middle_rate"}},{"text":"    Custom ","color":"dark_gray","hoverEvent":{"action":"show_text","value":"Let's you decide what mobs should be use to spawn plushies (Default: minecraft:pig). \u00a7f[ \u00a79Config file located inside datapack at: \u00a75data/plushie_settings/tags/entity_types/spawner.json \u00a7f]"}},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"\u25c7","color":"aqua","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/show_custom"}},{"text":"\n "}]


# CUSTOMGEN = 0, Showing Custom
#     Middle Rate [◇]       Custom [◆]
execute if entity @s[tag=showCustom] unless score CUSTOMGEN _plushieSettings matches 1 run tellraw @s ["",{"text":" \u0020 \u0020 Middle Rate ","color":"yellow"},{"text":"[\u25c7]","color":"gray"},{"text":"    Custom ","color":"dark_gray","hoverEvent":{"action":"show_text","value":"Let's you decide what mobs should be use to spawn plushies (Default: minecraft:pig). \u00a7f[ \u00a79Config file located inside datapack at: \u00a75data/plushie_settings/tags/entity_types/spawner.json \u00a7f]"}},{"text":"[\u25c6]","color":"aqua"},{"text":"\n "}]
# CUSTOMGEN = 1, Showing Custom, RATE not 1
#     Middle Rate [◇]       Custom [◆]
execute if entity @s[tag=showCustom] if score CUSTOMGEN _plushieSettings matches 1 if score RATE_C _plushieSettings matches 1 run tellraw @s ["",{"text":" \u0020 \u0020 Middle Rate ","color":"yellow"},{"text":"[\u25c6]","color":"green"},{"text":"    Custom ","color":"gold","hoverEvent":{"action":"show_text","value":"Let's you decide what mobs should be use to spawn plushies (Default: minecraft:pig). \u00a7f[ \u00a79Config file located inside datapack at: \u00a75data/plushie_settings/tags/entity_types/spawner.json \u00a7f]"}},{"text":"[\u25c6]","color":"aqua"},{"text":"\n "}]
# CUSTOMGEN = 1, Showing Custom, RATE = 1
#     Middle Rate [◆]       Custom [◆]
execute if entity @s[tag=showCustom] if score CUSTOMGEN _plushieSettings matches 1 unless score RATE_C _plushieSettings matches 1 run tellraw @s ["",{"text":" \u0020 \u0020 Middle Rate ","color":"yellow"},{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/middle_rate"}},{"text":"\u25c7","color":"green","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/middle_rate"}},{"text":"]","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/middle_rate"}},{"text":"    Custom ","color":"gold","hoverEvent":{"action":"show_text","value":"Let's you decide what mobs should be use to spawn plushies (Default: minecraft:pig). \u00a7f[ \u00a79Config file located inside datapack at: \u00a75data/plushie_settings/tags/entity_types/spawner.json \u00a7f]"}},{"text":"[\u25c6]","color":"aqua"},{"text":"\n "}]

