execute if score CORE _plushieSettings matches 3 run tellraw @s ["",{"text":"["},{"text":"\u25c6","color":"green"},{"text":"] "},{"text":"Default Mode  ","color":"blue","hoverEvent":{"action":"show_text","value":"Performs the best in most situations."}}]
execute unless score CORE _plushieSettings matches 3 run tellraw @s ["",{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/default_mode"}},{"text":"\u25c6","color":"red","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/default_mode"}},{"text":"] ","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/default_mode"}},{"text":"Default Mode  ","color":"blue","hoverEvent":{"action":"show_text","value":"Performs the best in most situations."}}]

execute if score CORE _plushieSettings matches 0 run tellraw @s ["",{"text":"["},{"text":"\u25c6","color":"green"},{"text":"] "},{"text":"Accuracy Mode  ","color":"red","hoverEvent":{"action":"show_text","value":"Runs smoothly when there are a very limited amount of plushies in the world [ Most operations run at the same time ]."}},{"text":"{Legacy}","color":"gold","hoverEvent":{"action":"show_text","value":"Runs smoothly when there are a very limited amount of plushies in the world due to most operations run at the same time."}}]
execute unless score CORE _plushieSettings matches 0 run tellraw @s ["",{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/accuracy"}},{"text":"\u25c6","color":"red","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/accuracy"}},{"text":"] ","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/accuracy"}},{"text":"Accuracy Mode  ","color":"red","hoverEvent":{"action":"show_text","value":"Runs smoothly when there are a very limited amount of plushies in the world [ Most operations run at the same time ]."}},{"text":"{Legacy}","color":"gold","hoverEvent":{"action":"show_text","value":"Runs smoothly when there are a very limited amount of plushies in the world due to most operations run at the same time."}}]

execute if score CORE _plushieSettings matches 2 run tellraw @s ["",{"text":"["},{"text":"\u25c6","color":"green"},{"text":"] "},{"text":"Performance Mode  ","color":"green","hoverEvent":{"action":"show_text","value":"Runs smoothly when there aren't many plushies in the world loaded at the same time."}},{"text":"{Legacy}","color":"gold","hoverEvent":{"action":"show_text","value":"Runs smoothly when there aren't many plushies in the world loaded at the same time."}}]
execute unless score CORE _plushieSettings matches 2 run tellraw @s ["",{"text":"[","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/performance"}},{"text":"\u25c6","color":"red","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/performance"}},{"text":"] ","clickEvent":{"action":"run_command","value":"/function plushiemenu:commands/performance"}},{"text":"Performance Mode  ","color":"green","hoverEvent":{"action":"show_text","value":"Runs smoothly when there aren't many plushies in the world loaded at the same time."}},{"text":"{Legacy}","color":"gold","hoverEvent":{"action":"show_text","value":"Runs smoothly when there aren't many plushies in the world loaded at the same time."}}]

tellraw @s {"text":"\n"}